use_frameworks!

platform :ios, '15.0'

target 'coin98-wallet-core_Example' do
  pod 'coin98-wallet-core', :path => '../'

  target 'coin98-wallet-core_Tests' do
    inherit! :search_paths

    
  end
end
